# production
# mysql://b4b70a84648266:666bde64@us-cdbr-iron-east-03.cleardb.net/heroku_ae687cd19ed1678?reconnect=true
development:
  adapter: mysql2
  encoding: utf8
  database: pingpong
  username: root
  password:
  host: 127.0.0.1
  port: 3306